# Generated by Django 4.0.2 on 2022-02-08 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('salary', models.IntegerField()),
                ('age', models.DateTimeField()),
                ('addarcard', models.ImageField(upload_to='image/')),
            ],
        ),
    ]
