# Generated by Django 4.0.2 on 2022-02-08 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='salary',
            field=models.CharField(max_length=100),
        ),
    ]
