# Generated by Django 4.0.2 on 2022-02-09 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_account_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='salary',
            field=models.IntegerField(default=True),
        ),
    ]
