# Generated by Django 4.0.2 on 2022-02-10 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_account_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Del_Account',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('salary', models.IntegerField(default=True)),
                ('age', models.DateTimeField()),
                ('addarcard', models.ImageField(upload_to='image/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
            ],
        ),
    ]
